### ISSUE TITLE
Porting to GDExtension

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#333]
This issue tracks the state of this module in regards to GDExtension.

It has been a long term goal to port this module to a dynamic library that can be shipped as a Godot plugin, which would allow using official Godot versions instead of having to recompile the editor and export templates. This makes distributing way easier through the asset library.
However it wasn't done in Godot 3 because GDNative had annoying issues in its design, but in Godot 4 it was rewritten as GDExtensions. This gets rid of some of the design problems, and the engine devs want it to be a true alternative to actually *porting* modules for real.

There are, however, still issues with it at the moment (Godot 4 is still in alpha). For that reason, porting will still not happen immediately, but hopefully it should happen somewhere in Godot 4.x versions. They are not necessarily blockers, but if solved, would make maintaining and using the library way easier.

### Main issues with the current state of GDExtensions and its C++ bindings

- [ ] **C# support**: there is no easy way to get access to classes in the library in C#. Same state as in GDNative, where you have to use slow `Call`, `Get` and `Set` with function names as string and no typing at all. So far only a module can expose an API.
- [ ] **Cannot call Godot methods from constructors**: this was also a problem in GDNative but was solved by defining a secondary constructor named `_init()`, which is called after the `owner` pointer is set. This was lost during the rewrite for GDExtensions so the problem is back.
- [ ] **Method typing checks**: this seemed to not work in GDNative. Calling a GDNative function from GDScript did not seem to check arguments types, or argument count. They were casted silently for the better or for the worse. This may need a second check in GDExtension because I haven't tried it yet.
- [ ] **No separation of editor and release libraries**: just like the editor comes in two versions (editor and export templates), libraries must be able to do this too. However I don't recall GDNative having that feature. This may need a second check in GDExtension.
- [ ] **Pointer access to typed arrays**: this was possible in GDNative, but got lost during the rewrite of GDExtension.
- [ ] **Singleton support**: because GDNative were considered scripts there was no other way to make singletons than to make the user create an autoload. This is not convenient. C++ modules can create singletons, but I'm not sure if GDNextension exposes that yet.
- [ ] **First load issue**: seen on RocketChat: when classes need to run in editor, there is a loading order bug which prevents libraries from working the first time after being added to the project. The editor needs to be closed and reopened again. This is a bad experience for plugin users.
- [ ] **Missing plugin registration**: there is no way to add an EditorPlugin through GDExtensions. The only way  is to use a `plugin.cfg` pointing to a script which then calls into the extension. Besides, `plugin.cfg` can register only one plugin, while this module contains more than one.
- [ ] **Documentation support**: the classes appear in the editor documentation pages but they don't have descriptions. That feature should be planned but appears to not be implemented yet.
- [ ] **Non-exposed APIS**: some functions used by this module are not accessible through GDExtension. Need to investigate and make a precise list.
- [ ] **WebAssembly support**: this is relatively low priority but as far as I remember, there doesnt seem to be an easy way to make web libraries.
- [ ] **No custom icons**: In GDScript, you can set custom icons to custom types either as a second argument to `class_name`, or by using `add_custom_type` from an editor plugin. This seems to be missing from GDExtension.

### Repository restructuration

Porting to GDExtension will make the module a plugin. That means the file structure will change, as there will be a few more things to include to it (helper scripts, shaders...), and it would be nice to not have all the folders about different things all at the same level. The C++ part will not change too much, but it will be moved to a lower-level folder. This structrure is not set in stone, it's mostly a draft.

```
.git/
.github/
bin/
    libvoxel-editor.dll
    libvoxel.dll
    ...
cpp/
    .gdignore
    terrain/
    meshers/
    util/
    ...
    thirdparty/
        meshoptimizer/
        godot-cpp/
        ...
    SConstruct
assets/
    icons/
    shaders/
    ...
doc/
    .gdignore
    source/
    ...
misc/
    .gdignore
    check_ci_result.py
voxel.gdextension
README.md
LICENSE.md
```

Note: contrary to many other addons, this structure will not start from the root of a Godot project. Everything will be the contents of what would be inside `res://addons/zylann.voxel/`. This makes it easier to submodule in other projects. The AssetLibrary package will still contain a full hierarchy.

**Comment by BastiaanOlij** [comment]
> No separation of editor and release libraries: just like the editor comes in two versions (editor and export templates), libraries must be able to do this too. However I don't recall GDNative having that feature. This may need a second check in GDExtension.

This one should be resolved, debug builds are needed for the editor, release builds can be released with the end result. You do so like this:
```
[libraries]

linux.64.debug="res://addons/godot-openvr/bin/x11/libgodot_openvr_debug.so"
linux.64.release="res://addons/godot-openvr/bin/x11/libgodot_openvr_release.so"
windows.64.debug="res://addons/godot-openvr/bin/win64/libgodot_openvr_debug.dll"
windows.64.release="res://addons/godot-openvr/bin/win64/libgodot_openvr_release.dll"
```

Note though that currently exporting extensions is broken, you have to copy the library in place manually

**Comment by nonunknown** [comment]
@Zylann In case you need, I've made some scripts to accelerate the development with gdextension, in case you need something to ease it for you just tell me: 

https://github.com/nonunknown/gdextension-creator

**Comment by Zylann** [comment]
After a week of work, I just finished introducing a new build target in the `gdextension` branch. This is only a first pass, so it should compile on Windows, but it is completely untested for now.

They are tracked in the source code of this project as `// TODO GDX: [...]` comments.

I'll probably open issues/PRs myself and reference them here later.

Notes:
- Some of these issues are worse than they look because this project supports compiling both as a module and an extension now.
- These issues were found *only by compiling the project*. I haven't run anything yet, so there is likely a lot more to discover.

GDextension/GodotCpp issues
-----------------------------

### Major

- [ ] `ClassDB::register_abstract_class` doesn't seem to have an equivalent. It isn't possible to bind an abstract class (unrelated to the C++ idiom, this is an existing Godot-specific feature), which means *classes that don't work as-is* will be shown to users in dropdowns and creation dialogs.
- [ ] There doesn't seem to be a way to register a non-exposed class. That means editor tools will pollute the `Add Node` dialog (TODO investigate if that really is true, maybe they can simply be not registered, but I have a doubt). Same concern was raised in https://github.com/godotengine/godot/pull/65592
- [ ] `GodotCpp` only defines two targets: `debug` (big unoptimized binary with debug checks) and `release` (small optimized binary without debug checks), which it assumes being "Editor" and "Exported game". There is no equivalent preset for `release_debug` (small optimized binary with debug checks), which is what Godot Editor official builds are using. This missing target is required for plugins. See https://github.com/godotengine/godot-cpp/pull/835
- [ ] No idea how to bind virtual methods that can be implemented by scripts? `GDVIRTUAL*` method binding appears to be missing. This is required for users to implement custom generators and implement some functions. `ClassDB::bind_virtual_method` exists but only seems used in wrapper classes and there is no example of it in the demo.
- [ ] `callable_mp` is not available. It allows to create a `Callable` from a method pointer. Without it, all methods we want to connect to signals have to be registered manually, like in the pre-Callable era.
- [ ] `PropertyInfo` requires a `const char*` for `name` and `hint_string` (unlike modules, where they are `String`). This makes it difficult to use formatted strings, which are very useful when the name or hint depends on a variable. In `_bind_methods` it is relatively safe to format an `std::string` and send `.c_str()` because Godot makes a `String` copy internally in the call to `bind_method`. However, in `_get_property_list` that trick isn't possible because the `const char*` has to be returned to the caller, it would have to outlive the method. See https://github.com/godotengine/godot-cpp/pull/826
- [ ] TO DOUBLE CHECK: someone raised that libraries compiled with the `release` target from GodotCpp cannot be used with a Godot Editor compiled with `release_debug` (aka official editor builds). If that's true, *it prevents shipping plugins to users* with GDExtension. Needs to be tested to confirm.
- [ ] Constants in classes like `Node::NOTIFICATION_*` are not declared static, therefore they take space in every instance, and cannot be used in `switch` statements, amongst other things. They are supposed to be static, or better, be declared as enums. This can be fixed in https://github.com/godotengine/godot-cpp/pull/828/files
- [ ] Methods taking a class derived from `Object` (like `SceneTree*` or `Node*`) cannot be bound. It causes a compiler error. This is supposed to be working. Workaround is to use `Object*` and cast manually.
- [ ] Inheriting from a custom class that overrides a virtual method fails to compile. For example, `A` implements `_get_configuration_warnings`, and `B` derives from `A` without overriding it. `GDCLASS` calls `register_virtuals`, which in turn calls `BIND_VIRTUAL_METHOD(B, _get_configuration_warnings)`, where `T` is the derived class. The problem might be that `B` does not actually define `_get_configuration_warnings`, its base class does. Oddly enough, this situation works fine if the base class is a core class, but it does not work if the base is also a custom class. This issue also makes it a nightmare when supporting both module and extension targets, as making wrappers isn't fully working (example https://github.com/Zylann/godot_voxel/blob/gdextension/editor/vox/vox_scene_importer.h).
- [ ] `EditorImportPlugin::_import` is passing `platform_variants` and `gen_files` as `const` arrays. They are supposed to be modifiable, for the method to fill them in. It makes the method unusable and confusing. Workaround is to `const_cast` them, which is ugly.
- [ ] `ClassDB::add_compatibility_class` is missing from in GDExtension.


### Minor

- [ ] `GDCLASS` defines `create`, a common name, which prevents anyone from binding a `create` function directly. A wrapper is necessary.
- [ ] `Math::is_nan`, `Math::is_inf`, `Math::deg_to_rad`, etc. are missing. They are found in `UtilityFunctions` instead, but in GDExtension it is desirable to have an inline version in `Math`, for performance.
- [ ] `_err_flush_stdout` is missing, so error macros generating a crash are unable to tell Godot to flush all pending log messages.
- [ ] `ThreadWorkPool` is missing Godot thread hooks. I have no use for it, but noticed it uses `std::thread` instead of `godot::Thread`. That means Godot hooks will not work here. This is not obvious and should really be indicated. Alternatively, Godot thread hooks should be exposed.
- [ ] Adding custom build options causes warnings. Following the example's `SConstruct` file (which nests `GodotCpp`'s `SConstruct` file by calling it), adding custom command line variables causes warnings in `GodotCpp`'s `SConstruct` file: `"WARNING: Unknown SCons variables were passed and will be ignored"`. This is a false-alarm though. The check `GodotCpp` does should not be where it is in a setup like this, it should be in the library's `SConstruct` (once all options were added), unless a better solution exists?
- [ ] `varray` is not available. It is useful to create an `Array` in using a single expression.
- [ ] `vformat` is not available. It is useful to create formatted strings with variables in a single expression.
- [ ] `Dictionary` is very inefficient to iterate, worse than GDScript. The only way apparently is to get a copy of all the keys with `.keys()`, iterate keys and then get each element this way. I don't know if a solution exists.
- [ ] `TypedArray<T>` is missing. It is used in modules to expose an `Array` with a type that isn't necessarily a built-in type (like a class), but in GodotCpp it's not available. Workaround is to use `Array`. See https://github.com/godotengine/godot-cpp/pull/841
- [ ] `SNAME` for inline-registered `StringNames` is missing.
- [ ] `TTR` is missing. It is necessary for showing localized editor-specific messages to users.
- [ ] `godot::Basis.elements` is a different name than `Basis.rows` in core. After a quick comparison of the `get_column` method, it seems `elements` is the same as `rows` (transposed matrix), but it would be better to fix the naming to make it explicit that this is exactly the same struct as in core.
- [ ] `GDCLASS` requires the presence of `_bind_methods()`, while in modules, this is optional.
- [ ] Missing version of `Object::cast_to` for `const T*`, cannot cast constant pointers
- [ ] `Transform3D::translated_local()` is missing
- [ ] Including `object.hpp` when defining a custom class inheriting `Object` does not compile. The `GDCLASS` macro requires `ClassDB`, which is not available in this specific case. `core/class_db.hpp` has to be included too. Although, this problem seems to also exist in core. So maybe there is no possible fix.
- [ ] Enum types in method arguments and return values aren't typed as they should be, if the type comes from another class. Example: in `EditorInspectorPlugin._parse_property`, `type` should be `Variant::Type` but instead is exposed as `int64_t`. That makes the function signature needlessly different in strongly typed languages, and it becomes more annoying when it has to be overriden.
- [ ] Any object type cannot be forward-declared when used in virtual method override *declarations*, even if taken by reference `&`. This is due to how `register_virtuals` is implemented in parent classes, which requires the full definition of `T`. That means we have to include the full classes for arguments like `Ref<InputEvent>&` or `Camera3D*` for example, slowing down compilation a bit.


Godot issues
--------------

- [ ] `Thread` is not exposing the static method to set the name of the thread. The voxel engine uses threads heavily. It makes them harder to spot with C++ debuggers.
- [ ] `Resource::duplicate` cannot be overriden (scripts can't do it either). But modules can override it, and the function is virtual in core. It prevents from porting classes using it in the voxel engine. This mostly leads to performance degradation, and possibly unexpected behavior (until I re-investigate all existing code that was using it).
- [ ] All extension class method arguments in editor docs show up as `unnamed`, despite being provided in the C++ code.
- [ ] Methods returning an object instance always show `Object` in editor docs, instead of the actual type, unlike methods from core classes.
- [ ] `Basis::get_rotation_quat` should be renamed `get_rotation_quaternion`. In Godot core it has the right name, but the script API still has the old shortened one, so does GodotCpp. 
- [ ] `ProjectSettings` lacks a function or parameter to tell that a custom setting requires an editor restart. This could be specified with `PROPERTY_USAGE_RESTART_IF_CHANGED` but `usage` is not handled by `add_property_info`.
- [ ] `RenderingServer::is_low_end()` is not exposed. It is therefore not possible to know automatically if the renderer supports creating resources from different threads.
- [ ] `RefCounted::reference_get_count()` is not exposed. It is then not possible to run debug checks in case we expect a place to hold the last ownership.
- [ ] `Geometry2D::make_atlas` returns the `size` of the resulting atlas as a `Vector2`, but should be `Vector2i`.
- [ ] Unnecessary return type difference in `get_configuration_warnings`. In the script API and GDExtension, `_get_configuration_warnings` returns a  `PackedStringArray`. But in Godot core, the return type is `TypedArray<String>` (an array of `Variant` with a type hint). This difference is unnecessary because `String` is a builtin type for which `PackedStringArray` exists. This is an issue due to compiling both as a module and an extension.
- [ ] `Node3D::NOTIFICATION_LOCAL_TRANSFORM_CHANGED` is not exposed in the API.
- [ ] `PROPERTY_USAGE_READ_ONLY` is not exposed in the API.
- [ ] `EditorProperty` is not exposing the virtual method `_set_read_only`. It prevents from making custom read-only property controls.
- [ ] Some virtual methods that previously took an `Object*` (or derived) now take a `Variant`. They weren't taking `Variant` in Godot 3, and still take `Object*` internally, so this looks like a regression. Found so far: `EditorPlugin._handles`, `EditorPlugin._edit`, `EditorInspectorPlugin._handles`... It is annoying in strongly typed languages, and even more annoying when compiling both as module and extension.
- [ ] In `EditorPlugin`, `_forward_3d_gui_input` returns an `AfterGUIInput` enum that belongs to the same class, but the enum is actually not present in GodotCpp. TODO Check again in more recent versions, it seems it was exposed in the docs.
- [ ] `EditorInspector::get_selected_path` is not exposed.
- [ ] `EDSCALE` is not available in GodotCpp, and the Godot API doesn't seem to expose an equivalent. This is required to implement DPI-aware editor tools.
- [ ] `SceneTree::get_process_time()` is not exposed. It would be convenient to have when using `_notification` instead of `_process` (due to source compatibility between module/extension).
- [ ] `RenderingDevice` has a singleton used by `RenderingServer`, but it cannot be accessed. Therefore it seems not possible to query its limits. Workaround?

**Comment by IPlayKindred** [comment]
any updates on this? how far is the godot 4 extension release?

**Comment by Zylann** [comment]
There has been a bit of progress, GodotCpp has solved some issues, and the extension can actually run in the editor (https://github.com/Zylann/godot_voxel/issues/581).
But it still isn't ready for production, as it lacks a lot of testing and crashes could still occur.

**Comment by Shadowblitz16** [comment]
@Zylann I would be willing to test the gdextension version with C#
